on:
  rss:
    url: https://github.com/ronething-bot/ifttt-release-demo/releases.atom
    # url: https://github.com/ruanyf/weekly/releases.atom
    config:
      limit: 3
      timeZone: Asia/Shanghai
jobs:
  operation:
    name: Rss Operation
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo link: $link
      - name: rewrite url
        id: set-link
        uses: actions/github-script@v4
        env:
          link: ${{ on.rss.outputs.link }}
        with:
          script: |
            let { link } = process.env
            console.log("link is", link)
            let tags = link.split("/")
            console.log("tags is", tags)
            let tag = tags[tags.length-1]
            console.log("tag is", tag)
            let newLink = `https://github.com/ruanyf/weekly/blob/master/docs/${tag}.md`
            console.log("new link is", newLink)
            return newLink
      - name: Make a HTTP Request      
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.SLACK_URL }}
          method: POST
          body: |
            {
              "text": "${{on.rss.outputs.title}} ${{on.rss.outputs.link}} <<<${{ steps.set-link.outputs.result }}>>>"
            }
