on:
  rss:
    url: https://github.com/ruanyf/weekly/releases.atom
    config:
      limit: 2
      timeZone: Asia/Shanghai
jobs:
  operation:
    name: Rss Operation
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo link: $link
      - name: Extract string
        id: extract_string
        run: |
          string=${{ on.rss.outputs.link }}
          issue=${string##*/}
          echo "issue is ${issue}"
          echo "ISSUE=$issue" >> $GITHUB_ENV
      - name: Post To Slack
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.SLACK_URL }}
          method: POST
          body: |
            {
              "text": "${{on.rss.outputs.title}} ${{ env.ISSUE }}"
            }
      # - name: Post To WeCom
      #   uses: actionsflow/axios@v1
      #   with:
      #     url: ${{ secrets.WECOM_URL }}
      #     method: POST
      #     body: |
      #       {
      #         "msgtype": "text",
      #         "text": {
      #           "content": "${{on.rss.outputs.title}} ${{steps.set-link.outputs.result}}"
      #         }
      #       }
