on:
  rss:
    # url: https://github.com/ronething-bot/ifttt-release-demo/releases.atom
    # url: https://github.com/ruanyf/weekly/releases.atom
    url: https://blog.ronething.cn/atom.xml
    config:
      limit: 2
      timeZone: Asia/Shanghai
jobs:
  operation:
    name: Rss Operation
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo link: $link
      - name: Extract string
        id: extract_string
        run: |
          string="https://github.com/ruanyf/weekly/releases/tag/issue-260"
          issue=${string##*/}
          echo "ISSUE=$issue" >> $GITHUB_ENV
      - name: Post To Slack
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.SLACK_URL }}
          method: POST
          body: |
            {
              "text": "${{on.rss.outputs.title}} ${{ ISSUE }}"
            }
      # - name: Post To WeCom
      #   uses: actionsflow/axios@v1
      #   with:
      #     url: ${{ secrets.WECOM_URL }}
      #     method: POST
      #     body: |
      #       {
      #         "msgtype": "text",
      #         "text": {
      #           "content": "${{on.rss.outputs.title}} ${{steps.set-link.outputs.result}}"
      #         }
      #       }
